# Generated by Django 5.0.4 on 2024-04-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeraccount',
            options={'verbose_name': 'Buyer Account', 'verbose_name_plural': 'Buyer Accounts'},
        ),
    ]
