# Generated by Django 5.0.4 on 2024-05-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_original_location',
            new_name='product_origin',
        ),
    ]
