# Generated by Django 5.0.4 on 2024-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'To pack'), (2, 'To ship'), (3, 'To deliver')], null=True),
        ),
    ]
