# Generated by Django 5.0.4 on 2024-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_account_user_alter_order_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'To pack'), (2, 'To ship'), (3, 'To deliver'), (4, 'Canceled')], null=True),
        ),
    ]
