# Generated by Django 5.0.6 on 2024-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'To pack'), (2, 'To ship'), (3, 'To deliver'), (4, 'Canceled')], default=1, null=True),
        ),
    ]
